### ISSUE TITLE
Uncaught Exception on Refresh

### ISSUE THREAD

**Issue by odie2828** [jmathai/foursquare-async#4]
I am new to OAuth and this is my code that gets the token.

<?php
$consumer_key = "YJ3JHCURSLNYZCZ4DFKTGO50TKKM03Z1AR3F5OXTTT4LD1HH";
$consumer_secret = "UHS3MDDUNZDXB2JJ1LADCWSQY23NEJRJTSFVCAOFU3EJWM5I";

require_once('EpiCurl.php');
require_once('EpiOAuth.php');
require_once('EpiFoursquare.php');

session_start();
$foursquareObj = new EpiFoursquare($consumer_key, $consumer_secret);
$foursquareObj->setToken($_REQUEST['oauth_token'],$_SESSION['secret']);
$token = $foursquareObj->getAccessToken();
$foursquareObj->setToken($token->oauth_token, $token->oauth_token_secret);

// user details
$foursquareUSER = $foursquareObj->get_user();
$user_details = $foursquareUSER->response;

//user history
$foursquareHIST = $foursquareObj->get_history();
$user_history = $foursquareHIST->response;
$i=0;
?>

Any time i refresh this page or paste the URL into another tab i get the following error:

Fatal error: Uncaught exception 'EpiOAuthUnauthorizedException' in /home/xxxxxxxxxx:374 Stack trace: #0 /home/xxxxxxxxxxxxxx(346): EpiOAuthException::raise(Object(EpiCurlManager), false) #1 /home/xxxxxxxxxxxxx(17): EpiOAuthResponse->__get('oauth_token') #2 {main} thrown in /home/xxxxxxxxxxxxxxx.php on line 374

Any advice or insight would be greatly appreciated.

**Comment by nedwidek** [comment]
Make sure that you are storing the token and secret correctly and not regenerating them. I had this error too and it turned out that I hadn't watched what I was doing in CakePHP closely enough. I was overwriting the pair when the callback was executed via my app_controller (oops).

The issue that I found most vexing was that I couldn't even catch that exception. Placing everything in a try-catch and catching EpiOAuthUnauthorizedException or EpiOAuthException still led to a CakePHP error page. I've never had an issue like that before when I've loaded vendor libraries. I'd like to catch it and 'log' them out. Still need to go back and do more testing to see if it is Cake, my server, or Foursquare-Async.  I do look forward to the patch where these are translated to EpiFoursquareException and its children.

**Comment by odie2828** [comment]
Yes, that was one thing that i accidently did, i was storing them as values but overwriting on the callback page.

Also, a HUGE thing that creates this error is if your callback page and/or your website URL that you register with foursquare, if they are set to "www.your-domain.com" and you are accessing the "Login Via foursquare" page via "your-domain.com" you will get thrown:

"Fatal error: Uncaught exception 'EpiOAuthUnauthorizedException' in /home/xxxxxxxxxx:374 Stack trace: #0 /home/xxxxxxxxxxxxxx(346): EpiOAuthException::raise(Object(EpiCurlManager), false) #1 /home/xxxxxxxxxxxxx(17): EpiOAuthResponse->__get('oauth_token') #2 {main} thrown in /home/xxxxxxxxxxxxxxx.php on line 374"

This is how i resolved this with PHP, instead of changing anything with my domain forwarding:

<?php
$host = $_SERVER['HTTP_HOST'];
if($host != "www.your-domain.com"){
header("Location: http://www.your-domain.com/");
exit;
?>

Added that code to the top of my index.php in the root.

**Comment by ssx** [comment]
Are you still having issues when using this library odie2828?

**Comment by jmathai** [comment]
Closing..
